- replace:
    path: /etc/kubernetes/kubelet.conf
    regexp: 'server:.*'
    replace: "server: https://{{ virtual_ip }}:6443"
    backup: no

- name: restart kubelet
  systemd: 
    name: kubelet 
    daemon_reload: yes
    state: restarted
    enabled: yes