- name: Get config map for the kube-proxy
  shell: kubectl get configmap -n kube-system kube-proxy -o yaml > /tmp/kube-proxy-cm.yaml

- replace:
    path: /tmp/kube-proxy-cm.yaml
    regexp: 'server:.*'
    replace: "server: https://{{ virtual_ip }}:6443"
    backup: no
   
- name: Apply the change to the config map
  shell: kubectl apply -f /tmp/kube-proxy-cm.yaml --force

- name: Delete all kube-proxy instances to nake them restart with the new configuration
  shell: kubectl delete pod -n kube-system -l k8s-app=kube-proxy