- hosts: all-masters[0]
  become: yes
  vars:
    upgrade_version: v1.9.6
    kubeadm_version: latest
  ignore_errors: yes
  roles:
    - kubeadm-upgrade

- hosts: all-vms
  serial: 1
  become: yes
  vars:
    kubelet_version: latest
  roles:
    - { role: update-kubelet, when: "groups['all-masters'][0] != inventory_hostname" }

